### ISSUE TITLE
Symbolic link on a ntfs external hard drive

### ISSUE THREAD

**Issue by GuyBencteux** [dooblem/bsync#31]
Hi, 
I am a new user of bsync and I find it extremely useful. 
I don't have any issue when synchronizing two machines running under ubuntu 16.04. 
Now I am trying to synchronize with my external USB hard drive, ntfs formatted. 

I have the following issue : 
- at the first synchronization, all seem to go well
- at the second, I get the following error message : 
> Error: difference in snaps for path: 

followed by the name of a file that is a symbolic link. And no way to get rid of it. 

I've made some tests : this message does not appear when synchronizing to a USB key formatted ext4, but appear with the ones formatted ntfs. 

I really would like to keep my external hard drive ntfs because I need to make regularly transfer with machines running Windows OS. 
How do you understand the error message I get ? Is there a way to pass by ? 

Thanks. (below, the complete session)

> cleobuline 21/11/2016 17:08:44 /home/guy : bsync -iv 01-Math/ /media/guy/Hypathie/01-Math/
> Loading filelists...
> Loading original filelist from snap files...
> Old filelist not found. Starting with empty history.
> Loading dir1 filelist...
> Loading dir2 filelist...
> Analysing original paths...
> Analysing remaining new paths in dir1...
> Analysing remaining new paths in dir2...
> 
> (LEFT DIR CONTENT)                                                                                                  (RIGHT DIR CONTENT)                                                                                            (ACTION)
> 
> programme_agregation.txt~                                                                                      -->                                                                                                                 (copy)
> liens_et_docs_20161017.txt~                                                                                    -->                                                                                                                 (copy)
> 
> Todo in 01-Math/: 
> Todo in /media/guy/Hypathie/01-Math/: cp:2
> Apply actions? [y/N] y
> 
> Applying actions...
> Applying actions in dir2...
> rsync: liens_et_docs_20161017.txt~
> rsync: programme_agregation.txt~
> Applying actions in dir1...
> Updating filelists...
> Updating snap files: .bsync-snap-20161121170918.712810...
> Done!

First is OK... Now I synchronize a second time : 

> cleobuline 21/11/2016 17:09:20 /home/guy : 
> cleobuline 21/11/2016 17:09:20 /home/guy : bsync -iv 01-Math/ /media/guy/Hypathie/01-Math/
> Loading filelists...
> Loading original filelist from snap files...
> Loading .bsync-snap-20161121170918.712810...
> Error: difference in snaps for path: Geometrie/Combes_Algebre_et_geometrie_ed1_v1.pdf
> cleobuline 21/11/2016 17:09:23 /home/guy : 
> cleobuline 21/11/2016 17:09:24 /home/guy : 
> 
This file  _Geometrie/Combes_Algebre_et_geometrie_ed1_v1.pdf_ is a symbolic link

**Comment by dooblem** [comment]
Hello,
Sorry for the late answer. I'm not able to reproduce.
To help me, can you send me the two .bsync-snap-XXX files (present in both directories) ?
Thanks in advance,
Marc

**Comment by dooblem** [comment]
feel free to send me the info and re-open.
