### ISSUE TITLE
is there a way to ignore hidden files 

### ISSUE THREAD

**Issue by alialwashli** [dooblem/bsync#33]
when i use the script for my home folder on linux , it copies all .file (hidden files) ,if you add this option to ignore hidden files , i would be very happy.

**Comment by tomachinz** [comment]
i would like to hide a lot of files, for example:

```
.npm/*
node_modules/*
```

can't get this to work?

**Comment by dooblem** [comment]
Hello @alialwashli 
sorry for the late answer.
For now it's not possible.

You can either:

- add all dotfiles dotdirectories in the .bsync-ignore file:
```
.npm
.node_modules
```
- tweak a bit get_ignores and ignorepath function in bsync
