### ISSUE TITLE
Keep a watch

### ISSUE THREAD

**Issue by pyaf** [dooblem/bsync#37]
I've used bsync and it is awesome. How can we use it to keep a watch on the local changes and synchronize the host and remote on real-time?

**Comment by dooblem** [comment]
Hello,

Like rsync, bsync is not really designed for real time synchronization.
You may try to script something with the inotifywait command, but I will suggest you to choose another tool for that. (I have synching or mutagen tools in mind...)

**Comment by pyaf** [comment]
Okay. Thanks
